### ISSUE TITLE
Добавить в сообщение о "Сохранение силы" ссылку на пост за который не было апвоута

### ISSUE THREAD

**Issue by hlushko** [vikxx/bots#1]
При активном использовании ботов для голосования, возникают ситуации, когда мощность голоса падает ниже нижнего предела. Тогда бот показывает уведомление, что он не проголосовал за пост, поскольку мощность просела:
![](http://joxi.net/Y2Lyzkau9zN05A.jpg)

Было б удобно, если б в этом сообщении была ссылка на пост, за который не был отдан голос. Поскольку, это мог быть какой-то важный пост, за который я б таки решил проголосовать вручную.

Возможно, это больше актуально для пользователей, которые ботов используют, как оповещение о новых постах авторов, которые нравятся.

Актуально для ботов серии: @steemrobot и @betarobot

Спасибо )

**Comment by vikxx** [comment]
>была ссылка на пост, за который не был отдан голос. Поскольку, это мог быть какой-то важный пост, за который я б таки решил проголосовать вручную.

Следует учесть, что таких постов будет много, так как процесс восстановление силы может занять много часов. 
Можно присылать уведомления о таких пропущенных постах и добавить к ним кнопку - для принудительного голоса :)

**Comment by hlushko** [comment]
> Следует учесть, что таких постов будет много, так как процесс восстановление силы может занять много часов.

Так они уже приходят. Просто сейчас это просто заглушка и все, информации о том, что это был за пост нету...

Было бы удобно знать, за какой именно пост, не был отдан голос. А если добавить возможность принудительного голоса через телеграмм, то было бы вообще супер 😊

**Comment by vikxx** [comment]
Добавлено

![image](https://user-images.githubusercontent.com/26347159/32049729-d9f33b84-ba56-11e7-8cd6-a5b6980b761e.png)

**Comment by hlushko** [comment]
Супер! Благодарю! 😄
