### ISSUE TITLE
Функция слежение за фаворитами

### ISSUE THREAD

**Issue by dinosmike** [vikxx/bots#10]
Сделать простую и удобную возможность следить за постами фаворитов, просто выдавать уведомления о выходе новых постов (и репостов ), но никаких действий не производить. 

Уведомление должно по идее иметь только три кнопки: **Читать, Коммент, Проголосовать**

Примерный макет прилагаю.

![screen](https://user-images.githubusercontent.com/7307409/32390451-8ccbe100-c0df-11e7-89fe-03bda79c4e09.jpg)

**Comment by vikxx** [comment]
Реализовано в https://t.me/betarobot
Этой ночью будет перенесено в остальные боты.
(обновления будут происходить ночью, что бы во время обрыва отсрочки не были пропущены посты - ночью их почти не размещают)

Включить опцию можно вводом команды `menu` и выборов соответствующей настройки. 
Настройки стали более компактными для удобства восприятия: #6 

![image](https://user-images.githubusercontent.com/26347159/32393247-64b7ab34-c0e1-11e7-975e-ac4e3e59554b.png)

Посты приходят пока в таком виде:

![image](https://user-images.githubusercontent.com/26347159/32393452-2c5943fa-c0e2-11e7-99d4-bbf2a9c01d4a.png)

Есть баг с дублированием некоторых постов, в процессе решения.

**Comment by dinosmike** [comment]
@vikxx про баг с дублированием постов - нашел проблему, если нажать "подписка и фаворит" то этот пользователь добавляется в список фаворитов ещё раз, и поэтому потом дублируются уведомление. Разве тут вообще нужна эта кнопка, может она лишняя?

**Comment by vikxx** [comment]
> Разве тут вообще нужна эта кнопка, может она лишняя?

Она может быть удобна.
Предполагается формировать ленту не только из тех на кого подписан, но и просто по всем постам.

Или например по тегу.

Например мне интересны статьи под тегом `api` - но поскольку тег могут ставить просто так, я бы хотел подписываться только на авторов интересных статей.
Я включаю режим "только чтение", указываю интересные мне теги, далее получаю список постов в виде сообщений. Если автор интересен - я добавляю его в фавориты/подписки.

**Comment by dinosmike** [comment]
Ну в таком случае она не должна дублировать фаворита в списке, и это решает проблему.

**Comment by dinosmike** [comment]
Пример списка, если я несколько раз нажал эту кнопку:
![image](https://user-images.githubusercontent.com/7307409/32404660-4df98dd4-c165-11e7-9bf7-da736863ccca.png)

**Comment by dinosmike** [comment]
А так же в Голосе происходит вот это, некрасиво))
![image](https://user-images.githubusercontent.com/7307409/32404725-b623964c-c166-11e7-9231-c1f42ea8a363.png)

**Comment by dinosmike** [comment]
@vikxx  Уведомления приходят многократно, если фаворит редактирует, по идее так быть не должно.

![image](https://user-images.githubusercontent.com/7307409/32418171-c0549778-c275-11e7-981d-14a6f3d3e5e1.png)
